export const companyOptions = [
    'Ayala Corporation',
    'San Miguel Corporation',
    'SM Investments Corporation',
    'JG Summit Holdings, Inc.',
    'Manila Electric Company (Meralco)',
    'Globe Telecom, Inc.',
    'PLDT Inc.',
    'BPI (Bank of the Philippine Islands)',
    'Metrobank (Metropolitan Bank and Trust Company)',
    'First Gen Corporation',
    'International Container Terminal Services, Inc. (ICTSI)',
    'Aboitiz Power Corporation',
    'DMCI Holdings, Inc.',
    'Meralco (Manila Electric Company)',
    'Landbank of the Philippines',
    'Alliance Global Group, Inc.',
    'Filinvest Development Corporation',
    'Robinsons Land Corporation',
    'Cebu Pacific Air',
    'Jollibee Foods Corporation',
];
